version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: info_company
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./src/main/resources:/liquibase/resources
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && liquibase --defaultsFile=/liquibase/resources/liquibase.properties update"

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/info_company
      DB_USERNAME: postgres
      DB_PASSWORD: password
      MONGODB_URI: mongodb://mongo:27017/info_company_test
      MONGODB_DATABASE: info_company_test
    depends_on:
      - liquibase
      - mongo

volumes:
  mongo-data:
